global EMPTY_POINT
EMPTY_POINT = " - "
global PLR_POINT
PLR_POINT = " * "
global PLR_WAITING
PLR_WAITING = "Waiting"
global PLR_GOING
PLR_GOING = "Going"
global PLR_DONE
PLR_DONE = "Done"
global PLR_HIT
PLR_HIT = "Hit"
global GRID_SIZE
GRID_SIZE = 25
global BLOCK_SIZE
BLOCK_SIZE = 20
global PLR_NUM
PLR_NUM = 5
global BLOT_NUM
BLOT_NUM = 3
global BLOT_MIN
BLOT_MIN = 2
global BLOT_MAX
BLOT_MAX = 4
global BLOT_PRINT
BLOT_PRINT = " X "
global BLOT_TIMEOUT
BLOT_TIMEOUT = 9
global BLOT_ACTIVE
BLOT_ACTIVE = 1
global BLOT_INACTIVE
BLOT_INACTIVE = 0
global SLEEP_TIME
SLEEP_TIME = .5
global PRINTING
PRINTING = False
